##import turtle # we need this to make turtles
##roop= turtle.Turtle () # read this as "roop is a turtle". We need a turtle in order to draw
##roop.pensize(5) 
##roop.color("pink")
##roop.penup()
##roop.backward(200)
##roop.pendown()
##roop.left(90) 
##roop.forward(200)
##roop.right(90)
##roop.forward(100)
##roop.right(90)
##roop.forward(75)
##roop.right(90)
##roop.forward(100)
##roop.left(130)
##roop.forward(150)
##roop.pensize(10)
##roop.color("grey")
##roop.penup() # she lifts her pen up here
##roop.left(50)
##roop.forward(50)
##roop.pendown() 
##roop.left(90)
##roop.forward(175)
##roop.right(90)
##roop.forward(90)
##roop.right(90)
##roop.forward(175)
##roop.right(90)
##roop.forward(90)
##roop.pensize(15)
##roop.color("light blue")
##roop.penup() # she lifts her pen up here
##roop.backward(140)
##roop.pendown() 
##roop.right(90)
##roop.forward(175)
##roop.right(90)
##roop.forward(90)
##roop.right(90)
##roop.forward(175)
##roop.right(90)
##roop.forward(90)
##roop.pensize(20)
##roop.color("light yellow")
##roop.penup() # she lifts her pen up here
##roop.backward(140)
##roop.penup() # she lifts her pen up here
##roop.right(90)
##roop.pendown() 
##roop.forward(175)
##roop.right(90)
##roop.forward(90)
##roop.right(90)
##roop.forward(90)
##roop.right(90)
##roop.forward(90)
