#Review
import turtle
screen = turtle.Screen() # create a Screen object
screen.setup(600,600) # big square screen
screen.bgcolor("red") # background colour
jaymit = turtle.Turtle()
jaymit.speed(0)
jaymit.forward(300)
screen.bgcolor("orange")

jaymit.left(180)
jaymit.forward(600) # when jaymit hits the wall
screen.bgcolor("yellow") # the background colour changes

jaymit.left(180)
jaymit.forward(600)
screen.bgcolor("green")

jaymit.left(180)
jaymit.forward(600)
screen.bgcolor("blue")

jaymit.left(180)
jaymit.forward(600)
screen.bgcolor("purple")

jaymit.left(180)
jaymit.forward(600)
screen.bgcolor("pink")

screen.clear()
jaymit.reset()
jaymit.speed(0)

#Challenge 1: Pinwheel
jaymit.penup()
jaymit.goto(0,0)
jaymit.pendown()
jaymit.pencolor("black")
jaymit.pensize(5)

jaymit.fillcolor("red")
jaymit.begin_fill()
jaymit.circle(100)
jaymit.end_fill()
jaymit.left(60)

jaymit.fillcolor("orange")
jaymit.begin_fill()
jaymit.circle(100)
jaymit.end_fill()
jaymit.left(60)

jaymit.fillcolor("yellow")
jaymit.begin_fill()
jaymit.circle(100)
jaymit.end_fill()
jaymit.left(60)

jaymit.fillcolor("green")
jaymit.begin_fill()
jaymit.circle(100)
jaymit.end_fill()
jaymit.left(60)

jaymit.fillcolor("blue")
jaymit.begin_fill()
jaymit.circle(100)
jaymit.end_fill()
jaymit.left(60)

jaymit.fillcolor("purple")
jaymit.begin_fill()
jaymit.circle(100)
jaymit.end_fill()
jaymit.left(60)

screen.clear()
jaymit.reset()
jaymit.speed(0)

#Challenge 2: Abstract art
jaymit.penup()
jaymit.color("green")
jaymit.goto(110,-70)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(30)
jaymit.end_fill()

jaymit.penup()
jaymit.color("grey")
jaymit.goto(-11,10)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(10)
jaymit.end_fill()

jaymit.penup()
jaymit.color("light blue")
jaymit.goto(45,120)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(20)
jaymit.end_fill()

jaymit.penup()
jaymit.color("teal")
jaymit.goto(-250,-255)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(15)
jaymit.end_fill()

jaymit.penup()
jaymit.color("magenta")
jaymit.goto(80,70)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(5)
jaymit.end_fill()

jaymit.penup()
jaymit.color("light green")
jaymit.goto(30,-210)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(16)
jaymit.end_fill()

jaymit.penup()
jaymit.color("red")
jaymit.goto(-130,67)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(11)
jaymit.end_fill()

jaymit.penup()
jaymit.color("brown")
jaymit.goto(50,-70)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(8)
jaymit.end_fill()

jaymit.penup()
jaymit.color("pink")
jaymit.goto(-145,-69)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(18)
jaymit.end_fill()

jaymit.penup()
jaymit.color("purple")
jaymit.goto(230,58)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(23)
jaymit.end_fill()

jaymit.penup()
jaymit.color("orange")
jaymit.goto(-150,300)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(13)
jaymit.end_fill()

jaymit.penup()
jaymit.color("yellow")
jaymit.goto(250,-270)
jaymit.pendown()
jaymit.begin_fill()
jaymit.circle(26)
jaymit.end_fill()

screen.clear()
jaymit.reset()
jaymit.speed(0)

#Challenge 3: Snowflake
jaymit.penup()
jaymit.goto(0,0)
jaymit.pendown()
jaymit.pencolor("blue")
jaymit.pensize(5)

jaymit.forward(150)
jaymit.backward(30)
jaymit.left(60)
jaymit.forward(30)
jaymit.backward(30)
jaymit.right(120)
jaymit.forward(30)
jaymit.backward(30)
jaymit.left(60)
jaymit.backward(120)
jaymit.left(60)

jaymit.forward(150)
jaymit.backward(30)
jaymit.left(60)
jaymit.forward(30)
jaymit.backward(30)
jaymit.right(120)
jaymit.forward(30)
jaymit.backward(30)
jaymit.left(60)
jaymit.backward(120)
jaymit.left(60)

jaymit.forward(150)
jaymit.backward(30)
jaymit.left(60)
jaymit.forward(30)
jaymit.backward(30)
jaymit.right(120)
jaymit.forward(30)
jaymit.backward(30)
jaymit.left(60)
jaymit.backward(120)
jaymit.left(60)

jaymit.forward(150)
jaymit.backward(30)
jaymit.left(60)
jaymit.forward(30)
jaymit.backward(30)
jaymit.right(120)
jaymit.forward(30)
jaymit.backward(30)
jaymit.left(60)
jaymit.backward(120)
jaymit.left(60)

jaymit.forward(150)
jaymit.backward(30)
jaymit.left(60)
jaymit.forward(30)
jaymit.backward(30)
jaymit.right(120)
jaymit.forward(30)
jaymit.backward(30)
jaymit.left(60)
jaymit.backward(120)
jaymit.left(60)

jaymit.forward(150)
jaymit.backward(30)
jaymit.left(60)
jaymit.forward(30)
jaymit.backward(30)
jaymit.right(120)
jaymit.forward(30)
jaymit.backward(30)
jaymit.left(60)
jaymit.backward(120)
jaymit.left(60)

screen.clear()
jaymit.reset()
jaymit.speed(0)

#Challenge 4: Silly Walks

jaymit.penup()
jaymit.goto(-200,100)
jaymit.pendown()
jaymit.pencolor("purple")
jaymit.pensize(5)

jaymit.forward(50)
jaymit.left(90)
jaymit.forward(20)

jasmit=turtle.Turtle()
jasmit.speed(0)
jasmit.penup()
jasmit.goto(-200,100)
jasmit.pendown()
jasmit.pencolor("grey")
jasmit.pensize(5)
